from enum import Enum


class SPECIAL_FOLDER(Enum):
    APP_DATA_LOCAL_LOW = 4
    APP_DATA_ROAMING = 5
    APP_DATA_LOCAL = 3
    PROGRAM_FILES_X86 = 13
    PROGRAM_FILES = 11
    USER_PROFILE = 1
    DOCUMENTS = 7
    DOWNLOADS = 6
    APP_DATA = 2
    PICTURES = 9
    DESKTOP = 0
    VIDEOS = 8
    MUSIC = 10
    WINDIR = 12


class ENVIRONMENT_VARIABLE(Enum):
    COMPUTER_NAME = 3
    SYSTEM_DRIVE = 1
    SYSTEM_LANG = 2
    USER_NAME = 0
